apiVersion: v1
kind: Service
metadata:
  name: getway-service
  namespace: pitstop
spec:
  selector:
    app: getway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
